Add Cfssl module support

diff --git a/modules/install-consul/consul-manage b/modules/install-consul/consul-manage
--- a/modules/install-consul/consul-manage
+++ b/modules/install-consul/consul-manage
@@ -34,16 +34,18 @@ conf(){
 }
 EOF
 
-    if [ -f "${CONSUL_CERTDIR}/cert.pem" ] && [ -f "${CONSUL_CERTDIR}/cert-key.pem" ]; then
+    if openssl verify -purpose sslserver -CAfile "/etc/ssl/certs/cacerts_${DATACENTER}_${DOMAIN}.pem" "${CONSUL_CERTDIR}/cert.pem" \
+            && [ -f "${CONSUL_CERTDIR}/cert-key.pem" ]; then
         cat > "$CONSUL_CONFDIR/tls.json" <<EOF
 {
     "ports": {
       "https": 8503
     },
+    "ca_file": "/etc/ssl/certs/cacerts_${DATACENTER}_${DOMAIN}.pem",
     "cert_file": "${CONSUL_CERTDIR}/cert.pem",
     "key_file": "${CONSUL_CERTDIR}/cert-key.pem",
-    "verify_incoming": true,
-    "verify_outgoing": true
+    "verify_incoming": false,
+    "verify_outgoing": false
 }
 EOF
     else
@@ -57,7 +59,7 @@ EOF
 }
 EOF
     else
-        rm -f "${CONSUL_CONFDIR}/encrypt.conf"
+        rm -f "${CONSUL_CONFDIR}/encrypt.json"
     fi
 
     if ! "$CONSUL_BIN" validate "$CONSUL_CONFDIR"; then
@@ -69,8 +71,30 @@ EOF
 function check(){
     consul info > /dev/null 2>&1
 }
+
 function check_cluster(){
     consul operator raft list-peers | grep -q leader
+}
+
+function cfsslcert(){
+    set -e
+    cfsslhost=${CFSSL_HOST:-cfssl.service.${DATACENTER}.${DOMAIN}}
+    mkdir -p "$CONSUL_CERTDIR"
+
+    certs_json=$(curl --connect-timeout 1 --silent --fail \
+                      -d '{ "request": {"hosts":["127.0.0.1", "localhost"], "CN": "'${DOMAIN}'" },  "profile": "server"}'\
+                      https://$cfsslhost:${CFSSL_PORT:-8888}/api/v1/cfssl/newcert 2>/dev/null)
+
+    if  echo "$certs_json" | jq -r '.result.certificate' | openssl verify -purpose sslserver -CAfile "/etc/ssl/certs/cacerts_${DATACENTER}_${DOMAIN}.pem" 2>/dev/null; then \
+        # generating files in temp dir before copying it because a watcher on the directory CONSUL_CERTDIR may interrupt the current process
+        certs_dir_temp=$(mktemp -d)
+        echo "$certs_json" | jq -r '.result.certificate' > "${certs_dir_temp}"/cert.pem
+        echo "$certs_json" | jq -r '.result.private_key' > "${certs_dir_temp}"/cert-key.pem
+        mv "${certs_dir_temp}"/cert.pem "${certs_dir_temp}"/cert-key.pem "${CONSUL_CERTDIR}"/ && rmdir "${certs_dir_temp}"
+    else
+        log user.error "error while generating cert. exiting."
+        exit 1
+    fi
 }
 
 # transform an address or list of ipv4
@@ -158,7 +182,7 @@ start() {
     esac
 
     log user.info "Starting agent with opts: ${CONSUL_AGENT_OPTS[*]}"
-    consulbin agent "${CONSUL_AGENT_OPTS[@]}"
+    exec "$CONSUL_BIN" agent "${CONSUL_AGENT_OPTS[@]}"
 }
 
 reload() {
@@ -191,10 +215,6 @@ case $1 in
         log user.info "start"
         start
         ;;
-    stop)
-        log user.info "stop"
-        stop
-        ;;
     reload)
         log user.info "reload"
         reload
@@ -206,6 +226,10 @@ case $1 in
     check)
         log user.info "check"
         check
+        ;;
+    cfssl-cert)
+        log user.info "cfssl-cert"
+        cfsslcert
         ;;
     check-cluster)
         log user.info "check-cluster"
diff --git a/modules/install-consul/install-consul b/modules/install-consul/install-consul
--- a/modules/install-consul/install-consul
+++ b/modules/install-consul/install-consul
@@ -63,11 +63,23 @@ function assert_not_empty {
 # Install steps are based on: http://stackoverflow.com/a/31576473/483528
 function setup_systemd_services {
     local readonly username="$1"
-    sudo cp "$SCRIPT_DIR/consul.service" "/etc/systemd/system/consul.service"
-    sudo cp "$SCRIPT_DIR/consul.path" "/etc/systemd/system/consul.path"
+    sudo cp "$SCRIPT_DIR/update-ca-cert.service" "/etc/systemd/system/"
+    sudo cp "$SCRIPT_DIR/update-ca-cert.path" "/etc/systemd/system/"
+    sudo cp "$SCRIPT_DIR/consul.service" "/etc/systemd/system/"
+    sudo cp "$SCRIPT_DIR/consul.path" "/etc/systemd/system/"
+    sudo cp "$SCRIPT_DIR/consul-restart.service" "/etc/systemd/system/"
+    sudo cp "$SCRIPT_DIR/consul-restart.path" "/etc/systemd/system/"
+    sudo cp "$SCRIPT_DIR/consul-watch-cfssl.service" "/etc/systemd/system/"
+    sudo cp "$SCRIPT_DIR/consul-watch-cacerts.service" "/etc/systemd/system/"
+
     sudo sed -i -e s/User=consul/User=$username/g "/etc/systemd/system/consul.service"
     sudo sed -i -e "s,/opt/consul,$path,g" "/etc/systemd/system/consul.service"
-    sudo systemctl enable consul.path
+    sudo sed -i -e s/User=consul/User=$username/g "/etc/systemd/system/consul-watch-cfssl.service"
+    sudo sed -i -e s/User=consul/User=$username/g "/etc/systemd/system/consul-watch-cacerts.service"
+    sudo sed -i -e "s,/opt/consul,$path,g" "/etc/systemd/system/consul-watch-cfssl.service"
+    sudo sed -i -e "s,/opt/consul,$path,g" "/etc/systemd/system/consul-watch-cacerts.service"
+
+    sudo systemctl enable consul.path consul-watch-cfssl.service update-ca-cert.path consul-restart.path
 
     # disable firewalld. TODO: make a proper setup for consul
     if systemctl list-unit-files --all | grep -q firewalld.service; then
@@ -130,25 +142,27 @@ function install_binaries {
 
   log_info "Downloading Consul $version from $url to $download_path"
   curl -o "$download_path" "$url"
-   if [ "$sha256sum" != "$(sha256sum "$download_path" | awk '{print $1}')" ]; then
-       log_error "dl binary checksum error $sha256sum != $(sha256sum "$download_path" | awk '{print $1}')"
-       exit 1
+  if [ "$sha256sum" != "$(sha256sum "$download_path" | awk '{print $1}')" ]; then
+      log_error "dl binary checksum error $sha256sum != $(sha256sum "$download_path" | awk '{print $1}')"
+      exit 1
+  else
+      unzip -d /tmp "$download_path"
   fi
 
-  unzip -d /tmp "$download_path"
+  log_info "Copying binaires & scripts to $bin_dir/"
+  sudo cp /tmp/consul \
+       "$SCRIPT_DIR/consul-manage" \
+       "$SCRIPT_DIR/watch-cfssl.sh" \
+       "$SCRIPT_DIR/watch-cacerts.sh" \
+       "$SCRIPT_DIR/functions.sh" \
+       "$SCRIPT_DIR/defaults.conf" "$bin_dir/"
 
-  log_info "Moving Consul binary to $bin_dir/"
-  sudo mv "/tmp/consul" "$bin_dir/"
-  sudo chown "$username:$username" "$bin_dir/consul"
-  sudo chmod a+x "$bin_dir/consul"
-
-  log_info "Copying Consul run scripts to $bin_dir/"
-  sudo cp "$SCRIPT_DIR/consul-manage" "$bin_dir/"
-  sudo cp "$SCRIPT_DIR/functions.sh" "$bin_dir/"
-  sudo cp "$SCRIPT_DIR/defaults.conf" "$bin_dir/"
   sudo sed -i -e "s,/opt/consul,$path,g" "$bin_dir/defaults.conf"
   sudo chown -R "$username:$username" "$path"
-  sudo chmod a+x "$bin_dir/consul-manage"
+  sudo chmod a+x "$bin_dir/consul" \
+       "$bin_dir/consul-manage" \
+       "$bin_dir/watch-cfssl.sh" \
+       "$bin_dir/watch-cacerts.sh"
 }
 
 function install {
