Convert install-dnsmasq into tf module

diff --git a/modules/install-dnsmasq/install-dnsmasq b/modules/install-dnsmasq/install-dnsmasq
--- a/modules/install-dnsmasq/install-dnsmasq
+++ b/modules/install-dnsmasq/install-dnsmasq
@@ -27,21 +27,24 @@ function install_dnsmasq {
    log_info "Installing Dnsmasq"
 
    if [[ -n "$(command -v yum)" ]]; then
-    sudo yum update -y
-    sudo yum install -y dnsmasq
-    echo "prepend domain-name-servers 127.0.0.1;" | sudo tee -a "/etc/dhcp/dhclient.conf" > /dev/null
-    echo "conf-dir=$DNSMASQ_CONFIG_DIR" | sudo tee -a "/etc/dnsmasq.conf" > /dev/null
-  else
-    log_error "Could not find apt-get or yum. Cannot install on this OS."
-    exit 1
-  fi
+       log_info "Running centos install"
+       sudo yum update -y
+       sudo yum install -y dnsmasq
+       echo "prepend domain-name-servers 127.0.0.1;" | sudo tee -a "/etc/dhcp/dhclient.conf" > /dev/null
+       echo "conf-dir=$DNSMASQ_CONFIG_DIR" | sudo tee -a "/etc/dnsmasq.conf" > /dev/null
+       sudo mkdir -p /etc/systemd/system/dnsmasq.service.d
+       sudo cp "$SCRIPT_DIR/10-consul.conf" /etc/systemd/system/dnsmasq.service.d/
+   elif [[ -n "$(command -v coreos-install)" ]]; then
+       log_info "Running coreos install"
+       sudo cp "$SCRIPT_DIR/dnsmasq.service" /etc/systemd/system
+   else
+       log_error "Could not find apt-get or yum. Cannot install on this OS."
+       exit 1
+   fi
 
-  sudo mkdir -p /etc/systemd/system/dnsmasq.service.d
-  sudo cp "$SCRIPT_DIR/10-consul.conf" /etc/systemd/system/dnsmasq.service.d/
   sudo systemctl daemon-reload
   sudo systemctl enable dnsmasq.service
 }
 
 install_dnsmasq
 log_info "Dnsmasq install complete!"
-
